eventos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.pagina_inicio, name='pagina_inicio'),
    path('eventos/', views.eventos_museo, name='eventos_museo'),  
    path('ver_evento/', views.ver_evento, name='ver_evento'),  
    path('reservar_evento/', views.reservar_evento, name='reservar_evento'),  
]

info/urls.py
from django.urls import path, include
from . import views
from .views import pagina_inicio, info_museo

urlpatterns = [
    path('', pagina_inicio, name='pagina_inicio'),
    path('info/', views.info_museo, name='info_museo'),
]

museo/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.pagina_inicio, name='pagina_inicio'),  
    path('admin/', admin.site.urls),
    path('empleados/', include('empleados.urls')),
    path('info/', include('info.urls')),
    path('historia/', include('historia.urls')),
    path('eventos/', include('eventos.urls')),
    path('coleccion/', include('coleccion.urls')),
    path('organizador/', include('organizador.urls')),
    path('expedientes/', include('expedientes.urls')),
]

eventos/models.py
from django.db import models

class Reservar(models.Model):
    EVENTO_DEFAULT_TEXT = ""

    evento = models.CharField(max_length=100, default=EVENTO_DEFAULT_TEXT, editable=False)
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

eventos/forms.py
from dataclasses import fields
from django import forms
from .models import Reservar

class ReservarForm(forms.ModelForm):
    class Meta:
        model = Reservar
        exclude = ['evento']
        fields = ['nombre']
        

eventos/views.py
from django.shortcuts import render, redirect
from .forms import ReservarForm
from .models import Reservar

def reservar_evento(request):
    evento = request.GET.get('evento')
    if request.method == 'POST':
        form = ReservarForm(request.POST)
        if form.is_valid():
            reserva = form.save(commit=False)  # Obtener la instancia del formulario sin guardarla aún
            reserva.evento = evento  # Asignar el valor del evento a la instancia
            reserva.save()  # Guardar la instancia en la base de datos
            return redirect('ver_evento')  
    else:
        form = ReservarForm()

    return render(request, 'reservar_evento.html', {'form': form, 'evento': evento})


def pagina_inicio(request):
    return render(request, 'inicio.html')

def ver_evento(request):
    eventos = Reservar.objects.all()
    return render(request, 'ver_evento.html', {'eventos': eventos})

def eventos_museo(request):
    return render(request, 'eventos_museo.html')

eventos/templates/eventos_museo.html
<!DOCTYPE html>
<html>
<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@600&display=swap" rel="stylesheet">
    <title>Eventos del museo</title>

    <style>
        * {
            margin: 0;
            padding: 0;
            text-decoration: none;
            font-family: 'Quicksand', sans-serif;
        }
        .content-page {
            background-image: url(https://images.pexels.com/photos/19670/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2);
            width: 100%;
            background-size: cover;
            background-repeat: no-repeat;
            position: relative;
            min-height: 100vh;
        }
        h1 {
            text-align: center;
            font-size: 40px;
        }
        .actividades {
            padding: 20px;
        }
        .texto1 {
            /* background-color: #D71313; */
            width: 600px;
            height: 200px;
            margin-left: 50px;
        }
        .texto2 {
            width: 600px;
            height: 200px;
            margin-left: 50px;
        }
        .texto3 {
            width: 600px;
            height: 200px;
            margin-left: 50px;
        }
        .literatura-img {
            width: 300px;
            height: 200px;
            margin-left: 60px;
            /* border: 3px solid #ccc; */
            border-radius: 1cm;
        }
        .taller-img {
            width: 300px;
            height: 200px;
            margin-left: 70px;
            /* border: 3px solid #ccc; */
            border-radius: 1cm;
        }
        .ninos-img {
            width: 300px;
            height: 200px;
            margin-left: 10px;
            /* border: 3px solid #ccc; */
            border-radius: 1cm;
        }
        .regresar-button {
            margin-top: 30px;
            margin-left: 15px;
            width: 100px;
            height: 45px;
            border-radius: 2cm;
            border: 3px solid #ccc;
            border-color: #D71313;
            background-color: white;
            font-size: 15px;
            color: black;
        }
        .regresar-button:hover {
            background-color: #D71313;
        }
        .button-reservar1 {
            margin-bottom: 40px;
            margin-left: 20px;
            width: 100px;
            height: 45px;
            border-radius: 2cm;
            border: 3px solid #ccc;
            border-color: #91C8E4;
            background-color: white;
            font-size: 15px;
            color: black;
        }
        .button-reservar2 {
            margin-left: 20px;
            margin-bottom: 80px;
            width: 100px;
            height: 45px;
            border-radius: 2cm;
            border: 3px solid #ccc;
            border-color: #91C8E4;
            background-color: white;
            font-size: 15px;
            color: black;
        }
        .button-reservar3 {
            margin-left: 20px;
            margin-bottom: 60px;
            width: 100px;
            height: 45px;
            border-radius: 2cm;
            border: 3px solid #ccc;
            border-color: #91C8E4;
            background-color: white;
            font-size: 15px;
            color: black;
        }
        .button-reservar1:hover, .button-reservar2:hover, .button-reservar3:hover {
            background-color: #91C8E4;
        }
        .poesia {
            display: flex;
            align-items: center;
            margin-left: 20px;
        }
        .talleres {
            display: flex;
            align-items: center;
            margin-left: 20px;
            margin-top: 20px;
        }
        .actividades-ninos {
            display: flex;
            align-items: center;
            margin-left: 20px;
            margin-top: 20px;
        }

    </style>
</head>
<body>
    <div class="content-page">
        <a href="{% url 'pagina_inicio' %}"><button class="regresar-button">Regresar</button></a>
        <h1>Actividades</h1>
        <div class="actividades">
            <div class="poesia">
                <h2 class="titulo1">Poesía y literatura</h2>
                <img src="https://images.pexels.com/photos/1560093/pexels-photo-1560093.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="" class="literatura-img">
                <p class="texto1">Sumérgete en la fusión única de palabras y arte en nuestro evento de Poesía y Literatura. Experimenta la magia de la creación literaria mientras exploras las galerías, donde las palabras dan vida a las obras maestras. Disfruta de lecturas de poesía inspiradas en las exhibiciones. Este encuentro transcurre en un ambiente enriquecido por la convergencia de la expresión artística y literaria, creando un espacio donde las palabras danzan entre las obras de arte, revelando nuevas perspectivas y emociones. Únete a nosotros para una experiencia única que celebra la conexión entre la poesía y la creatividad visual en el corazón de nuestro amado museo.</p>
                <a href="{% url 'reservar_evento' %}?evento=Poesia%20y%20literatura"><button class="button-reservar1">Reservar</button></a>
            </div>    

            <div class="talleres">
                <h2>Talleres artísticos</h2>
                <img src="https://images.pexels.com/photos/542555/pexels-photo-542555.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="" class="taller-img">
                <p class="texto2">Experimenta con una variedad de técnicas y estilos, desde la pintura hasta la escultura, guiado por talentosos instructores. Estos talleres ofrecen a adultos y niños la oportunidad de explorar su expresión artística mientras se inspiran en las magníficas obras del museo. Únete a nosotros para una experiencia única, donde el arte no solo se contempla, sino que también se crea con tus propias manos.</p>
                <a href="{% url 'reservar_evento' %}?evento=Talleres%20artisticos"><button class="button-reservar2">Reservar</button></a>
            </div>

            <div class="actividades-ninos">
                <h2>Actividades para niños</h2>
                <img src="https://images.pexels.com/photos/4161111/pexels-photo-4161111.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="" class="ninos-img">
                <p class="texto3">Bienvenidos a un mundo de magia y aprendizaje en nuestras Actividades para Niños en el Museo Soumaya. Diseñadas especialmente para los más pequeños, estas actividades combinan diversión y educación en un entorno lleno de arte. Desde emocionantes búsquedas de tesoros hasta coloridas sesiones de creación artística, los niños explorarán la maravillosa conexión entre la imaginación y las obras maestras que alberga el museo. Celebra cumpleaños de manera única y estimulante, donde cada niño se convierte en un pequeño artista en este viaje de descubrimiento cultural.</p>
                <a href="{% url 'reservar_evento' %}?evento=Actividades%20para%20ninos"><button class="button-reservar3">Reservar</button></a>
            </div>
        </div>
    </div>
    <!-- Botón para regresar a la página de inicio -->
    

    <!-- <table class="default">
        <caption><h2>Actividades dentro del museo</h2></caption>
        <tr>
            <td>Poesía y literatura</td>
            <td>Sumérgete en la fusión única de palabras y arte en nuestro evento de Poesía y Literatura. Experimenta la magia de la creación literaria mientras exploras las galerías, donde las palabras dan vida a las obras maestras. Disfruta de lecturas de poesía inspiradas en las exhibiciones. Este encuentro transcurre en un ambiente enriquecido por la convergencia de la expresión artística y literaria, creando un espacio donde las palabras danzan entre las obras de arte, revelando nuevas perspectivas y emociones. Únete a nosotros para una experiencia única que celebra la conexión entre la poesía y la creatividad visual en el corazón de nuestro amado museo.</td>

            <td><a href="{% url 'reservar_evento' %}?evento=Cultura%20Mexica"><button>Reservar</button></a></td>
        </tr>
        <tr>
            <td>Cultura Olmeca</td>
            <td>Este es un evento que hablará de la cultura Olmeca</td>
            <td><a href="{% url 'reservar_evento' %}?evento=Cultura%20Olmeca"><button>Reservar</button></a></td>
        </tr>
        <tr>
            <td>Cultura Totonaca</td>
            <td>Este es un evento que hablará de la cultura Totonaca</td>
            <td><a href="{% url 'reservar_evento' %}?evento=Cultura%20Totonaca"><button>Reservar</button></a></td>
        </tr>
    </table> -->
    
</body>
</html>


eventos/templates/reservar_evento.html
<!DOCTYPE html>
<html>
<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@600&display=swap" rel="stylesheet">
    <title>Reservar Evento</title>

    <style>
        * {
            margin: 0;
            padding: 0;
            text-decoration: none;
            font-family: 'Quicksand', sans-serif;
        }
        .content-page {
            background-image: url(https://images.pexels.com/photos/19670/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2);
            width: 100%;
            background-size: cover;
            background-repeat: no-repeat;
            position: relative;
            min-height: 100vh;
        }
        .regresar-button {
            margin-top: 30px;
            margin-left: 15px;
            width: 100px;
            height: 45px;
            border-radius: 2cm;
            border: 3px solid #ccc;
            border-color: #D71313;
            background-color: white;
            font-size: 15px;
            color: black;
        }
        .regresar-button:hover {
            background-color: #D71313;
        }
        .eventos-button {
            margin-top: 200px;
            margin-left: 400px;
            width: 100px;
            height: 45px;
            border-radius: 2cm;
            border: 3px solid #ccc;
            border-color: #91C8E4;
            background-color: white;
            font-size: 15px;
            color: black;
        }
        .eventos-button:hover {
            background-color: #91C8E4;
        }
        .reservacion-button {
            margin-left: 200px;
            width: 120px;
            height: 45px;
            border-radius: 2cm;
            border: 3px solid #ccc;
            border-color: #91C8E4;
            background-color: white;
            font-size: 15px;
            color: black;
        }
        .reservacion-button:hover {
            background-color: #91C8E4;
        }

        h1 {
            text-align: center;
        }
        .input-reserva {
            margin-left: 100px;
            margin-top: 200px;
        }
        label {
            font-size: 30px;
        }
        input[type="text"] {
            width: 600px;
            padding: 8px;
            margin-bottom: 16px;
            box-sizing: border-box;
            font-size: 20px;
            border-radius: 1cm;
            border: 2px solid #ccc;
            border-color: black;
        }

        input[type="submit"] {
            width: 100px;
            height: 45px;
            border-radius: 2cm;
            border: 3px solid #ccc;
            border-color: #91C8E4;
            background-color: white;
            font-size: 15px;
            color: black;
        }
    </style>
</head>
    <body>
        <div class="content-page">
            <a href="{% url 'pagina_inicio' %}"><button class="regresar-button">Regresar a inicio</button></a>
            <h1>Reservar evento para "{{ evento }}"</h1>

            <div class="input-reserva">
                <form method="post">
                    {% csrf_token %}
                    <label for="id_nombre">Ingresa tu nombre completo:</label>
                    {{ form.nombre }}
                    <input type="submit" value="Reservar">
                </form>
                <!-- Botón para regresar a la página de inicio -->
                

                <a href="{% url 'eventos_museo' %}"><button class="eventos-button">Ver Eventos</button></a>
                
                <!-- Botón para ver la lista de eventos -->
                <a href="{% url 'ver_evento' %}"><button class="reservacion-button">Ver reservaciones</button></a>
        </div>
        </div>

    </body>
</html>

eventos/templates/ver_evento.html
<!DOCTYPE html>
<html>
<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@600&display=swap" rel="stylesheet">
    <title>Lista de Eventos Reservados</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            text-decoration: none;
            font-family: 'Quicksand', sans-serif;
        }
        .content-page {
            background-image: url(https://images.pexels.com/photos/19670/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2);
            width: 100%;
            background-size: cover;
            background-repeat: no-repeat;
            position: relative;
            min-height: 100vh;
        }
        h1 {
            text-align: center;
            font-size: 40px;
        }
        .evento {
            padding: 20px;
            border: 5px solid #ccc;
            margin: 20px 500px;
            text-align: center;
            border-color: #91C8E4;
        }
        .regresar-button {
            margin-top: 30px;
            margin-left: 15px;
            width: 100px;
            height: 45px;
            border-radius: 2cm;
            border: 3px solid #ccc;
            border-color: #D71313;
            background-color: white;
            font-size: 15px;
            color: black;
        }
        .regresar-button:hover {
            background-color: #D71313;
        }
        .reservar-button {
            margin-left: 670px;
            margin-top: 30px;
            width: 100px;
            height: 45px;
            border-radius: 2cm;
            border: 3px solid #ccc;
            border-color: #91C8E4;
            background-color: white;
            font-size: 15px;
            color: black;
        }
        .reservar-button:hover {
            background-color: #91C8E4;
        }
    </style>
</head>
<body>
    <div class="content-page">
    <a href="{% url 'pagina_inicio' %}"><button class="regresar-button">Regresar a inicio</button></a>
    <h1>Lista de Eventos Reservados</h1>
    {% for reservar in eventos %}
        <div class="evento">
            <strong>Evento:</strong> {{ reservar.evento }}<br>
            <strong>Nombre:</strong> {{ reservar.nombre }}<br>
        </div>
    {% endfor %}
    <div class="botones">
        
        <a href="{% url 'reservar_evento' %}"><button class="reservar-button">Reservar otro evento</button></a>
    </div>
</div>
</body>
</html>